### ISSUE TITLE
snapcastclient not starting

### ISSUE THREAD

**Issue by blueboysthlm** [bestlibre/hassio-addons#84] opened 2018-08-07 08:40 UTC
When i try to start snapcastclient I get the following error message:

/run.sh: line 8: snapclient: command not found

**Comment by mike6460** [comment] 2018-10-20 15:49
Did you figure this out?  I am getting the same error.

**Comment by jussbba** [comment] 2018-10-25 17:53
Me too, any solution?

**Comment by jussbba** [comment] 2018-12-14 13:43
Any updates on this?

**Comment by Teryeahh** [comment] 2018-12-14 14:17
Awsome! Will try when I get home

**Comment by Teryeahh** [comment] 2018-12-14 21:59
Not working.. Did you do anything to make it work? What Hass.io version are you running? and is the protecion mode on or off?

**Comment by jussbba** [comment] 2018-12-14 23:08
No, I just uninstalled snapclient and the installed it again. Protection mode seems to be enabled.

Did you put ip between ” ” these? I have it that way.

I am running 0.83.3, how about you?

**Comment by Teryeahh** [comment] 2018-12-14 23:48
Yes. I put IP between those. It is updates to the last version.. i still get the same error.. I guess this Addon is no longer maintained? No replies from the dev...?

**Comment by bestlibre** [comment] 2018-12-17 18:13
Duplicate of #91

**Closed** 2018-12-17 18:13 UTC
